# Generated by Django 5.2.9 on 2026-01-22 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0002_turma_professor_regente_alter_aluno_turma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='matricula_escolar',
            new_name='matricula',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedagogico.turma'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedagogico.disciplina'),
            preserve_default=False,
        ),
    ]
