# Generated by Django 5.2.9 on 2025-12-27 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedagogical', '0002_disciplina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('VIDEO', 'Vídeo Aula'), ('PDF', 'Material de Leitura (PDF)'), ('LINK', 'Link Externo'), ('TAREFA', 'Entrega de Trabalho')], max_length=10)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='lumenios/materiais/')),
                ('link_externo', models.URLField(blank=True, help_text='Link do YouTube ou site externo', null=True)),
                ('texto_apoio', models.TextField(blank=True, help_text='Descrição ou instruções')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('visivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='lumenios.modulo')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SalaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='lumenios/capas/')),
                ('descricao', models.TextField(blank=True, verbose_name='Sobre a Matéria')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogical.disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_lumenios', to='pedagogical.turma')),
            ],
        ),
        migrations.AddField(
            model_name='modulo',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='lumenios.salavirtual'),
        ),
        migrations.CreateModel(
            name='ProgressoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumenios.materialaula')),
            ],
            options={
                'unique_together': {('aluno', 'material')},
            },
        ),
    ]
