# Generated by Django 5.2.9 on 2026-01-20 17:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, default='SaaS_Head', max_length=50)),
                ('tenant_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_school',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('role', models.CharField(default='ALUNO', max_length=20, verbose_name='Cargo')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('cidade_natal', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade_atual', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('hobby', models.CharField(blank=True, max_length=100)),
                ('atuacao', models.CharField(blank=True, max_length=100, verbose_name='Atuação')),
                ('local_trabalho', models.CharField(blank=True, max_length=200, verbose_name='Local de Trabalho')),
                ('instituicao_ensino', models.CharField(blank=True, max_length=200, verbose_name='Instituição')),
                ('status_relacionamento', models.CharField(blank=True, max_length=50)),
                ('nivel_ensino', models.CharField(blank=True, default='medio', max_length=20, null=True)),
                ('fase_vida', models.CharField(blank=True, default='JOVEM', max_length=20, null=True)),
                ('tenant_type', models.CharField(default='PUBLIC', max_length=20)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_gestor', models.BooleanField(default=False)),
                ('is_aluno', models.BooleanField(default=False)),
                ('is_professor', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'core_customuser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
