# Generated by Django 5.2.9 on 2025-12-20 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedagogical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('DECLARACAO', 'Declaração'), ('HISTORICO', 'Histórico Escolar'), ('CONTRATO', 'Contrato de Prestação de Serviços'), ('CERTIFICADO', 'Certificado / Diploma'), ('OUTRO', 'Outro')], default='DECLARACAO', max_length=20)),
                ('conteudo', models.TextField(help_text='Use {{ aluno.nome }}, {{ aluno.cpf }}, etc. para campos dinâmicos.')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('conteudo_final', models.TextField(help_text='Conteúdo com as variáveis já substituídas')),
                ('codigo_validacao', models.CharField(editable=False, max_length=50, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pedagogical.aluno')),
                ('emitido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretariat.modelodocumento')),
            ],
        ),
    ]
