# Generated by Django 5.2.9 on 2025-12-20 17:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('nome', models.CharField(max_length=100)),
                ('ano_letivo', models.IntegerField(default=2025)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDeAula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('titulo', models.CharField(max_length=200)),
                ('data_prevista', models.DateField()),
                ('conteudo', models.TextField(blank=True)),
                ('habilidades_bncc', models.TextField(blank=True, help_text='Códigos da BNCC separados por vírgula')),
                ('objetivos', models.TextField(blank=True)),
                ('metodologia', models.TextField(blank=True)),
                ('recursos', models.TextField(blank=True)),
                ('avaliacao_texto', models.TextField(blank=True, verbose_name='Método de Avaliação')),
                ('status', models.CharField(choices=[('Planejado', 'Planejado'), ('Ministrado', 'Ministrado'), ('Adiado', 'Adiado')], default='Planejado', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_aula', to='pedagogical.turma')),
            ],
        ),
        migrations.CreateModel(
            name='DiarioClasse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('conteudo_lecionado', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plano_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedagogical.planodeaula')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogical.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Prova', 'Prova'), ('Trabalho', 'Trabalho'), ('Atividade', 'Atividade em Sala'), ('Simulado', 'Simulado')], default='Atividade', max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso na média final', max_digits=5)),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('unidade', models.CharField(choices=[('1ª Unidade', '1º Bimestre/Trimestre'), ('2ª Unidade', '2º Bimestre/Trimestre'), ('3ª Unidade', '3º Bimestre/Trimestre'), ('4ª Unidade', '4º Bimestre/Trimestre'), ('Recuperação', 'Recuperação Final')], default='1ª Unidade', max_length=20)),
                ('data_aplicacao', models.DateField()),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='provas/')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='pedagogical.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('nome', models.CharField(max_length=255)),
                ('matricula_id', models.CharField(blank=True, help_text='Código ou número de chamada', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email do aluno ou responsável', max_length=254, null=True)),
                ('telefone_responsavel', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='pedagogical.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('presente', models.BooleanField(default=True)),
                ('justificativa', models.CharField(blank=True, max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='pedagogical.aluno')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='pedagogical.diarioclasse')),
            ],
            options={
                'unique_together': {('diario', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Comentário do professor para o aluno')),
                ('situacao', models.CharField(choices=[('Normal', 'Entregue'), ('Pendente', 'Não Entregue'), ('Justificado', 'Falta Justificada')], default='Normal', max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='pedagogical.aluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_lancadas', to='pedagogical.atividade')),
            ],
            options={
                'unique_together': {('aluno', 'atividade')},
            },
        ),
    ]
