# Generated by Django 5.2.9 on 2025-12-19 15:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pedagogical', '0002_alter_aluno_options_alter_turma_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('aprovado_licitacao', models.BooleanField(default=False, help_text='Fornecedor homologado em licitação?')),
            ],
        ),
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('numero_processo', models.CharField(max_length=50)),
                ('modalidade', models.CharField(max_length=50)),
                ('objeto', models.TextField(help_text='Descrição do que está sendo comprado')),
                ('data_abertura', models.DateField()),
                ('valor_total_estimado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em Análise'), ('HOMOLOGADA', 'Homologada'), ('DESERTA', 'Deserta/Fracassada')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LocalizacaoPatrimonio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_alunos', models.IntegerField(default=100)),
                ('limite_armazenamento_gb', models.IntegerField(default=10)),
                ('permite_gestao_publica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoAluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('responsavel_financeiro', models.CharField(max_length=255)),
                ('cpf_cnpj_responsavel', models.CharField(max_length=20)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_financeiro', to='pedagogical.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='BoletoAluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('descricao', models.CharField(default='Mensalidade', max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido')], max_length=20)),
                ('link_pagamento', models.URLField(blank=True, null=True)),
                ('asaas_payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='financial.contratoaluno')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('descricao', models.CharField(max_length=255)),
                ('data_pedido', models.DateField(default=django.utils.timezone.now)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROVADO', 'Aprovado'), ('RECEBIDO', 'Recebido/Estoque'), ('PAGO', 'Pago')], default='SOLICITADO', max_length=20)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.fornecedor')),
                ('licitacao', models.ForeignKey(blank=True, help_text='Vincular a processo licitatório se houver', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.licitacao')),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('codigo_etiqueta', models.CharField(help_text='Número da plaqueta', max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('data_aquisicao', models.DateField()),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vida_util_anos', models.IntegerField(default=5, help_text='Para cálculo de depreciação (Ex: TI=5 anos, Móveis=10 anos)')),
                ('estado_conservacao', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('DANIFICADO', 'Danificado'), ('BAIXADO', 'Baixado/Descartado')], default='NOVO', max_length=20)),
                ('localizacao_atual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.localizacaopatrimonio')),
                ('compra_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.pedidocompra')),
            ],
        ),
        migrations.CreateModel(
            name='AssinaturaEscola',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INADIMPLENTE', 'Inadimplente'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20)),
                ('data_proxima_cobranca', models.DateField()),
                ('asaas_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='core.school')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.planosaas')),
            ],
        ),
    ]
