# Generated by Django 5.2.9 on 2025-12-30 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('titulo', models.CharField(max_length=100)),
                ('cbo', models.CharField(blank=True, help_text='Código Brasileiro de Ocupações', max_length=20)),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('nome', models.CharField(max_length=100)),
                ('codigo_centro_custo', models.CharField(blank=True, help_text='Para integração financeira', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField()),
                ('matricula', models.CharField(max_length=50)),
                ('data_admissao', models.DateField()),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ / Prestador'), ('ESTAGIO', 'Estagiário'), ('TEMPORARIO', 'Temporário'), ('CONCURSADO', 'Concursado (Público)')], default='CLT', max_length=20)),
                ('salario_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email_corporativo', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.departamento')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha_funcionario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gerente_departamento', to='hr.funcionario'),
        ),
    ]
