# Generated by Django 5.2.9 on 2026-01-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('aluno_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='ATIVA', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub_secretaria.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub_secretaria.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoSecretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub_secretaria.matricula')),
            ],
        ),
    ]
