# Generated by Django 5.2.9 on 2025-12-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
    ]
